package streamdeck

// Tile is a domain-neutral presentation generated by a control surface.
type Tile struct {
	Artwork            string
	Label, Value, Icon string
	Meter, LevelKnown  bool
	LevelDB            float64
}

// Frame contains one complete layout generation. Dial 6 is navigation.
type Frame struct {
	Generation uint64
	Keys       [Keys]Tile
	Dials      [Encoders]Tile
}

func renderFrame(f Frame) ([][]byte, []byte) {
	return renderChangedFrame(f, Frame{}, nil)
}

func renderChangedFrame(f, previous Frame, cached [][]byte) ([][]byte, []byte) {
	view := presentation{}
	for n, k := range f.Keys {
		view.Keys[n] = keyPresentation{Artwork: k.Artwork, Label: k.Label, Value: k.Value, Icon: k.Icon}
	}
	for n, k := range f.Dials {
		view.Knobs[n] = knobPresentation{Target: k.Label, Value: k.Value, Meter: k.Meter, LevelKnown: k.LevelKnown, LevelDB: k.LevelDB}
		if n == Encoders-1 {
			// Only the page dial carries text (the next page name) in Icon; a
			// control's icon is an identifier, never strip text.
			view.Knobs[n].Name = k.Icon
		}
	}
	tiles := make([][]byte, Keys)
	for n, k := range view.Keys {
		// Meter updates affect only the dial strip; reuse expensive static key JPEGs.
		if len(cached) >= Keys && k == (keyPresentation{Artwork: previous.Keys[n].Artwork, Label: previous.Keys[n].Label, Value: previous.Keys[n].Value, Icon: previous.Keys[n].Icon}) {
			tiles[n] = cached[n]
		} else {
			tiles[n] = renderKey(k)
		}
	}
	return tiles, renderKnobs(view.Knobs)
}
