package streamdeck

// Tile is a domain-neutral presentation generated by a control surface.
type Tile struct{ Label, Value, Icon string }

// Frame contains one complete layout generation. Dial 6 is navigation.
type Frame struct {
	Generation uint64
	Keys       [Keys]Tile
	Dials      [Encoders]Tile
}

func renderFrame(f Frame) ([][]byte, []byte) {
	view := presentation{}
	for n, k := range f.Keys {
		view.Keys[n] = keyPresentation{Label: k.Label, Value: k.Value, Icon: k.Icon}
	}
	for n, k := range f.Dials {
		view.Knobs[n] = knobPresentation{Target: k.Label, Value: k.Value, Name: k.Icon}
	}
	return renderPresentation(view)
}
