param([string]$Tags = "")
$ErrorActionPreference = "Stop"
Push-Location (Split-Path $PSScriptRoot -Parent)
$previousCache = $env:GOCACHE
try {
    & ./scripts/stop.ps1
    # Check before compiling the companion or touching either deployed binary.
    $companions = @(Get-ChildItem bin -Filter *.dll -ErrorAction SilentlyContinue | ForEach-Object Name)
    foreach ($name in ($companions + @("snoofer.exe", "snoofer-audio-monitor.dll", "snoofer-soundboard.dll", "snoofer-media.dll", "snoofer-aec.dll", "snoofer-camera.dll"))) {
        $path = Join-Path (Get-Location) "bin/$name"
        if (Test-Path -LiteralPath $path) {
            try {
                $probe = [IO.File]::Open($path, [IO.FileMode]::Open, [IO.FileAccess]::ReadWrite, [IO.FileShare]::None)
                $probe.Dispose()
            } catch {
                throw "Cannot replace bin/$name. Graceful shutdown did not release the file; inspect Snoofer before retrying. No alternate output will be created."
            }
        }
    }
    $go = Get-Command go -ErrorAction SilentlyContinue
    if ($go) { $goPath = $go.Source } else { $goPath = "$env:ProgramFiles\Go\bin\go.exe" }
    $env:GOCACHE = Join-Path (Get-Location) ".local/go-build"
    New-Item -ItemType Directory -Force bin | Out-Null
    $selected = $Tags -split '[, ]+'
    if ($selected -notcontains "core" -and $selected -notcontains "no_audio") {
        & ./scripts/build-monitor.ps1 -OutputDirectory bin
        if ($selected -notcontains "no_soundboard") { & ./scripts/build-soundboard.ps1 }
        if ($selected -notcontains "no_aec") { & ./scripts/build-aec.ps1 -OutputDirectory bin; & ./scripts/build-neural-aec.ps1 -OutputDirectory bin }
    }
    if ($selected -notcontains "core" -and $selected -notcontains "no_nowplaying") { & ./scripts/build-media.ps1 -OutputDirectory bin }
    if ($selected -notcontains "core" -and $selected -notcontains "no_insta360") { & ./scripts/build-camera.ps1 -OutputDirectory bin }
    # The GUI stylesheet is generated by the Tailwind CLI and embedded by Go.
    & npm run --silent css
    if ($LASTEXITCODE -ne 0) { throw "Tailwind CSS generation failed; run npm install first." }
    $css = Get-Item -LiteralPath "app/web/dist/app.css" -ErrorAction SilentlyContinue
    if (-not $css -or $css.Length -eq 0) { throw "app/web/dist/app.css is missing or empty; the GUI would be unstyled." }
    $arguments = @("build", "-trimpath", "-ldflags", "-H=windowsgui", "-o", "bin/snoofer.exe")
    $arguments += @("-tags", ("production " + $Tags).Trim())
    & $goPath @arguments ./cmd/snoofer
    if ($LASTEXITCODE -ne 0) { throw "Build failed. The only app output is bin/snoofer.exe." }
    Write-Output "Built: bin/snoofer.exe"
} finally {
    $env:GOCACHE = $previousCache
    Pop-Location
}
