// Copies the Lucide icons used by the desktop GUI from the pinned lucide-static
// dev dependency into app/web/icons.mjs. Rerun after changing ICONS.
const fs = require("node:fs");
const path = require("node:path");

const ICONS = [
  "audio-waveform", "music", "lightbulb", "layout-grid", "puzzle", "plug", "activity",
  "mic", "mic-off", "volume-2", "volume-x", "play", "square", "circle-dot", "skip-back", "skip-forward",
  "power", "headphones", "audio-lines", "sun", "link", "monitor", "layers", "waves", "sliders-horizontal",
  "circle", "minus", "plus", "chevron-left", "chevron-right", "copy", "check", "search", "house", "refresh-cw", "radar", "folder", "chevron-up", "chevron-down",
];

const root = path.resolve(__dirname, "..");
const pkg = path.join(root, "node_modules", "lucide-static");
const version = JSON.parse(fs.readFileSync(path.join(pkg, "package.json"), "utf8")).version;
const license = fs.readFileSync(path.join(pkg, "LICENSE"), "utf8").trim();
const bodies = {};
for (const name of ICONS) {
  const svg = fs.readFileSync(path.join(pkg, "icons", name + ".svg"), "utf8");
  const inner = /<svg[^>]*>([\s\S]*)<\/svg>/.exec(svg);
  if (!inner) throw new Error("unexpected SVG format: " + name);
  bodies[name] = inner[1].replace(/\s+/g, " ").replace(/> </g, "><").trim();
}

const out = `// Generated by scripts/vendor-icons.cjs from lucide-static ${version}. Do not edit.
/*
${license}
*/

const icons = ${JSON.stringify(bodies, null, 1)};

// icon returns an inline Lucide SVG that inherits the text color. Pass complete
// Tailwind class literals so the stylesheet build can find them.
export function icon(name, classes = "size-5 shrink-0") {
 const template = document.createElement("template");
 template.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"></svg>';
 const svg = template.content.firstElementChild;
 svg.setAttribute("class", classes);
 svg.dataset.icon = name in icons ? name : "circle";
 svg.innerHTML = icons[name] ?? icons.circle;
 return svg;
}

export const iconNames = Object.keys(icons);
`;
fs.writeFileSync(path.join(root, "app", "web", "icons.mjs"), out);
console.log("Wrote app/web/icons.mjs with " + ICONS.length + " Lucide " + version + " icons");
